name: Cast Highlight Scan
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  env:
    MY_COMPANY_ID: 16567

  workflow_dispatch:
  
jobs:
  scan:
    runs-on: ubuntu-latest
    # use the prod environment, where the secret CAST_HIGHLIGHT_API_TOKEN is defined
    environment: prod

    steps:
      - uses: actions/checkout@v2

      - name: scan project source code 
        env:
          HELLO_NODEJS_APP_ID: 105791
        run: |
          docker run --rm -v $(pwd):/s -v /tmp:/w  casthighlight/hl-agent-cli \
                                                   --sourceDir /s \
                                                   --workingDir /w \
                                                   --tokenAuth ${{ secrets.CAST_HIGHLIGHT_API_TOKEN }} \
                                                   --companyId ${{ env.MY_COMPANY_ID }} \
                                                   --applicationId ${{ env.HELLO_NODEJS_APP_ID }}  

