name: Cast Highlight Scan
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  scan:
    environment: prod
    container:
      image: casthighlight/hl-agent-cli
      volumes:
        - ${{ env.GITHUB_WORKSPACE }}:/s
        - /tmp/:/w
    env:
      CAST_HIGHLIGHT_API_TOKEN: ${{ secrets.CAST_HIGHLIGHT_API_TOKEN }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: scan project source code 
        uses: casthighlight/hl-agent-cli
        with: |
          args: --sourceDir /s --workingDir /w --tokenAuth ${{ CAST_HIGHLIGHT_API_TOKEN }} --companyId 16567 --applicationId 105791 

